language: python
sudo: false

env:
  - LUA="lua=5.3"
  # - LUA="luajit=2.0"
  # - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - cd lua-agent

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  # If there's 100 or less *warnings* it's probably ok? lol
  - luacheck --std max+busted *.lua --exclude-files *_spec.lua -g -d -t -q
  - busted --verbose --coverage

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install
